import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppBar, Box, Button, Toolbar, Typography } from "@mui/material";
import Link from "next/link";
import ThemeRegistry from "./ThemeRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Full Stack Homework",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body className={inter.className}>
          <AppBar position="static">
            <Toolbar>
              <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                <Button color="inherit" component={Link} href="/">
                  Alison
                </Button>
              </Typography>
              <Button color="inherit" component={Link} href="/numbers">Numbers</Button>
              <Button color="inherit" component={Link} href="/grades">Grades</Button>
            </Toolbar>
          </AppBar>
          <Box component="main" sx={{ p: 3 }}>
            {children}
          </Box>
        </body>
      </ThemeRegistry>
    </html>
  );
}
