CREATE TABLE numbers (
    id SERIAL PRIMARY KEY,
    value INTEGER NOT NULL
);

CREATE TABLE grades (
    id SERIAL PRIMARY KEY,
    class_name VARCHAR(255) NOT NULL,
    grade INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
